spring:
  application:
    name: cheappInv
  datasource:
    url: jdbc:h2:mem:cheappInv;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

inventory:
  outbox:
    enabled: true
    poll-interval: 2s
    batch-size: 50
  default-warehouse-id: MAIN

springdoc:
  swagger-ui:
    tryItOutEnabled: true
    operationsSorter: method
