spring:
  application:
    name: cheappInv

  # Perfil por defecto: dev (H2 en memoria)
  profiles:
    default: dev

logging:
  level:
    com.cheapp.cheappInv: INFO
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level [%X{correlationId}] %logger{36} - %msg%n"

# --------------------
# DEV (H2)
# --------------------
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: ${DB_URL:jdbc:h2:mem:postgres;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
    driver-class-name: org.h2.Driver
    username: postgres
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

management:
  endpoints:
    web:
      exposure:
        include: health,info

inventory:
  outbox:
    enabled: true
    poll-interval: 2s
    batch-size: 50
  default-warehouse-id: MAIN

springdoc:
  swagger-ui:
    try-it-out-enabled: true
    operations-sorter: method

app:
  cors:
    allowed-origins: http://localhost:5173

# --------------------
# POSTGRES
# --------------------
---
spring:
  config:
    activate:
      on-profile: postgres

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/cheappinv}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

# El resto de settings se heredan del documento dev (si quieres duplicarlos aquí, también vale)
